trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'devops-mini-project2'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build || echo "No build step"
  displayName: 'Install dependencies'

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHubConnection'
    repository: 'kesavakiran/devops-mini-project2'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: latest
  displayName: 'Build and Push Docker image'
